#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:  base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      #- CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      #- CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=172.16.2.129:5984
      #- CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      #- CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/hyperledger/crypto/peer
        - ./channel/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp/:/etc/hyperledger/crypto/orderer/msp
        - ../mount/peer0/var/hyperledger/production:/var/hyperledger/production
    #depends_on:
     #   - orderer.example.com
