#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: docker-compose.yaml
      service: orderer.example.com


