#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:


  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:  docker-compose.yaml
      service: peer0.org1.example.com
    extra_hosts:
      - "orderer.example.com:192.168.86.130"

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file:  docker-compose.yaml
      service: peer1.org1.example.com
    extra_hosts:
      - "orderer.example.com:192.168.86.130"
      - "peer0.org1.example.com:192.168.86.131"

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file:  docker-compose.yaml
      service: peer0.org2.example.com
    extra_hosts:
      - "orderer.example.com:192.168.86.130"

  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    extends:
      file:  docker-compose.yaml
      service: peer1.org2.example.com
    extra_hosts:
      - "orderer.example.com:192.168.86.130"
      - "peer0.org2.example.com:192.168.86.133"
