#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:
   couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file:  docker-compose.yaml
      service: peer0.org2.example.com
    extra_hosts:
      - "orderer.example.com:192.168.86.130"

